# Generated by Django 4.0.5 on 2022-06-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0002_alter_images_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
