# Generated by Django 4.0.5 on 2022-06-05 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0004_remove_images_user_images_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='likes',
            field=models.ManyToManyField(related_name='instagram', to=settings.AUTH_USER_MODEL),
        ),
    ]
